const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  closeApp: () => ipcRenderer.send('app:close'),
  minimizeApp: () => ipcRenderer.send('app:minimize'),
  openExternal: (url) => ipcRenderer.send('app:openExternal', url),
  openFolder: (folderPath) => ipcRenderer.send('app:openFolder', folderPath),
  onUpdateYtDlpAvailable: (callback) => ipcRenderer.on('update:yt-dlp-available', (event, data) => callback(data)),
  startYtDlpUpdate: () => ipcRenderer.invoke('update:yt-dlp-start'),
  readAudioFiles: (folderPath) => ipcRenderer.invoke('app:readAudioFiles', folderPath),
  renameFiles: (folderPath, tasks) => ipcRenderer.invoke('app:renameFiles', folderPath, tasks),
  getUsbDrives: () => ipcRenderer.invoke('app:getUsbDrives'),
  formatUsb: (driveLetter, label) => ipcRenderer.invoke('app:formatUsb', driveLetter, label),
  copyToUsb: (source, dest, files) => ipcRenderer.invoke('app:copyToUsb', source, dest, files),
  getFilesSize: (folderPath, files) => ipcRenderer.invoke('app:getFilesSize', folderPath, files),
  getFreeSpace: (folderPath) => ipcRenderer.invoke('app:getFreeSpace', folderPath),
  onCopyProgress: (callback) => ipcRenderer.on('copy:progress', (event, data) => callback(data)),
  selectFolder: () => ipcRenderer.invoke('dialog:selectFolder'),
  openTxtFile: () => ipcRenderer.invoke('dialog:openTxtFile'),
  fetchInfo: (options) => ipcRenderer.invoke('download:fetch-info', options),
  startDownload: (options) => ipcRenderer.invoke('download:start', options),
  onDownloadProgress: (callback) => ipcRenderer.on('download:progress', (_event, data) => callback(data)),
  removeDownloadProgressListener: () => ipcRenderer.removeAllListeners('download:progress'),
  onDenoMissing: (callback) => ipcRenderer.on('deno:missing', () => callback()),
  installDeno: () => ipcRenderer.invoke('deno:install'),
  stopDownload: () => ipcRenderer.invoke('download:stop'),
  checkAuthStatus: () => ipcRenderer.invoke('auth:check-status'),
  loginOAuth: () => ipcRenderer.invoke('download:login-oauth'),
  cancelOAuth: () => ipcRenderer.invoke('download:cancel-oauth'),
  logoutOAuth: () => ipcRenderer.invoke('download:logout-oauth'),
  onOAuthCode: (callback) => ipcRenderer.on('oauth:code', (_event, data) => callback(data)),
  removeOAuthListeners: () => ipcRenderer.removeAllListeners('oauth:code'),
  loginYouTube: () => ipcRenderer.invoke('auth:youtube-login'),
  checkCookieFile: () => ipcRenderer.invoke('auth:check-cookie-file'),
  fetchVideoInfo: (options) => ipcRenderer.invoke('video:fetch-info', options),
  startVideoDownload: (options) => ipcRenderer.invoke('video:download', options),
  onVideoProgress: (callback) => ipcRenderer.on('video:progress', (_event, data) => callback(data)),
  removeVideoProgressListener: () => ipcRenderer.removeAllListeners('video:progress'),
  stopVideoDownload: () => ipcRenderer.invoke('video:stop-download'),
});
